### ISSUE TITLE
Pointer Cursor missing from "Get Started" buttons

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#10]
The "Get Started" buttons have a highlight effect but no pointer cursor when hovering over.

Steps

Load http://www.iron.io
Hover over "Get Started" button in any of the product sections (e.g. IronWorker )

Expected Result
  Pointer Cursor
Actual Result
  Default Cursor

**Comment by odeits** [comment]
The btn class should probably have cursor: pointer to avoid this in the future.

**Comment by codydotio** [comment]
Edited and on staging
