### ISSUE TITLE
Please document default node and npm version

### ISSUE THREAD

**Issue by jayfresh** [iron-io/issues#100]
Hi,

I've just resolved some problems I was having getting `npm install` to build my package dependencies. It turns out that the default version of npm that ironworker uses (1.1.59) can't cope with some types of dependency specification e.g. `x.x.x^`. I've solved the problem by specifying `stack node-0.10` in my worker file, but I think it would have been really helpful to have known in advance that the default wasn't 0.10 (and associated npm version). The documentation page [here](http://dev.iron.io/worker/reference/dotworker/#syntax_reference) reference 0.10, which is misleading as it looks like a default.

Thanks,

J.

**Comment by rkononov** [comment]
Hey @jayfresh system environment description is here - http://dev.iron.io/worker/reference/environment/ , by default you're using 'default' stack with obsolete packages, unfortunately we can't migrate users to newer packages because we could break things, so we're forcing new users to use 'stack' parameter in .worker and select proper environment.

**Comment by jayfresh** [comment]
Hey, thanks for the response! That page says that the default node stack is node-0.10, but the default is node v0.8.8.

**Comment by rkononov** [comment]
it's not default it's stack you could select using 'stack' parameter in your .worker file.
Using stack you could customize the environment you're using.

**Comment by jayfresh** [comment]
There is an asterisk `*` next to the stack name: `node-0.10*` - at the bottom of the table it says, "*default language version if a specific "stack" is not declared in .worker file". If the default language version is v0.8.8 then the documentation as written is a little misleading, to me anyhow.

**Comment by jayfresh** [comment]
Hey guys, I see you've updated the docs to make it clearer that 0.8 is the default, so you can close this is you like.
