### ISSUE TITLE
Email Support Page is down

### ISSUE THREAD

**Issue by aviflax** [iron-io/issues#103]
I found a link to [this page](http://support.iron.io/customer/portal/emails/new) over [here](http://dev.iron.io/worker):

```
$ curl -i http://support.iron.io/customer/portal/emails/new
curl: (6) Could not resolve host: support.iron.io
```

**Comment by Stephenitis** [comment]
Hello Avi thanks for the notice. Can you email support@iron.io for now or click on the support button in our dashboard?

**Comment by aviflax** [comment]
Yup will do thanks.
