### ISSUE TITLE
After latest update it shows 404 error

### ISSUE THREAD

**Issue by kanggit** [iron-io/issues#105]
Yesterday when i did _composer update_, ironmq was updated to dev-master, so it was throwing _"Class IronMQ not found"_ issue. After going through issue discussions here I downgraded to _3.0.1_. Previous error disappeared but getting _404 Not found_ error.

When i debugged it was an issue with _api_version_ in latest version of code.

Below url throws 404.
_https://mq-aws-us-east-1.iron.io:443/3/projects/xxxxxxxxx/queues/my_queue/messages_

After changed _api_version_ in _IronMQ_ class as below it worked.

`protected $default_values = array(
        'protocol'    => 'https',
        'host'        => 'mq-aws-us-east-1.iron.io',
        'port'        => '443',
        'api_version' => '1',  //changed here
    );`

But i am not sure where to change this api version in my dashboard https://hud.iron.io/mq/aws.

It would be helpful to handle this in future(or, did I miss something for update?)

**Comment by thousandsofthem** [comment]
Please try library version "1.*"

**Comment by thousandsofthem** [comment]
Short summary. I'll update README
Branches:
- `1.*` - laravel-compatible, php-5.2-compatible version. No namespaces. Using default IronMQ servers.
- `2.*` - PSR-4 compatible version with namespaces. Using default IronMQ servers. If you're not using laravel stick with it.
- `3.*` - Special version for IronMQ API v3. Different API, different server endpoints. Go with it if you're using [IronMQ on-premise](http://dev.iron.io/mq-onpremise/)
- `master` branch - same as `2.*`

**Comment by kanggit** [comment]
Got it. I will fallback to 1.*
