### ISSUE TITLE
The Worker Getting Started page instruction is incorrect

### ISSUE THREAD

**Issue by John-Lin** [iron-io/issues#107]
Hi iron-io team, 

I found there is a instruction mistake in the Worker Getting Started page. In the **Upload Your Worker** section the zip command should be `zip -r hello_worker.zip .`

The instructions missing the dot which represent the current directory. It will confuse newbies.

![screen shot 2015-12-19 at 9 53 41 pm](https://cloud.githubusercontent.com/assets/4214069/11913340/a7cb683c-a69b-11e5-9152-096580816ab0.png)

**Comment by thousandsofthem** [comment]
Everything looks good now, closing
