### ISSUE TITLE
Iron.io Plan

### ISSUE THREAD

**Issue by servicedesk-missguided** [iron-io/issues#108]
Hi,

I’m not sure on the relevant contact in regards to this issue but we have been receiving alerts to our service desk stating the following:

“Used 131% of IronMQ plan amount”

I have had notification that we should be on the IronMQ Production Plan which allows for 100M API requests per month but instead we are still on a 1M API plan. It would seem that we have not moved over to this plan which is preventing us from sending to a particular set of customers.

I have attempted to call in regards to this issue but believe that with yourselves being based in the US that the office is currently closed, if someone could please look into this as a priority that would be much appreciated. Please feel free to call me on +44 0161 672 2526.

Kind regards,

Connor

E: connor.hobson@missguided.com
P: 0161 672 2526

**Comment by treeder** [comment]
Hi, this sounds like something you'll want to email support@iron.io about.
