### ISSUE TITLE
We run on, Push button provisioning images aren't clickable.

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#11]
These sections have links to clouds and services in the text but the images themselves aren't clickable.

Steps:
1. Load http://iron.io
2. Scroll to "Any Platform ...:
3. Hover over AWS Icon / Image

Expected Result:
- Image is a link 
- Image is clickable

Actual Result:
- Image is not a link 
- Image is not clickable

**Comment by odeits** [comment]
By moving the anchor tag for the text to include the image this will resolve the issue.

**Comment by codydotio** [comment]
This has been edited and is on staging
