### ISSUE TITLE
In your language logos don't have links

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#12]
Any Platform, Any Cloud, Any Language. Both Any Platform and Any Cloud have links to their respected sources; however, the Any Language section is just images with no links.

Steps:
1. Load http://www.iron.io
2. Scroll to Any Platform, Any Cloud, Any Language.
3. Click on PHP logo

Expected result:
- PHP website is loaded in new tab

Actual result:
- No op.

**Comment by codydotio** [comment]
This has been edited and is on staging
