### ISSUE TITLE
Learn How button in homepage slider doesn't have pointer

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#13]
Learn How button in the large homepage slider doesn't have cursor pointer.

Steps:
1. Load http://www.iron.io
2. hover over learn how button

Expected result:
- Pointer cursor

Actual result:
- default cursor

**Comment by odeits** [comment]
Relates to #10 however these are "button" classed and in issue #10 they are "btn" class

**Comment by codydotio** [comment]
Edited and on staging
