### ISSUE TITLE
[HUD] Project Link goes out of context.

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#17]
Description:
   Project Link always goes to  Worker, not the 'Getting Started' tab of the current section.

Steps:
1. Load the hud.
2. Select a MQ Project
3. Click 'Queues" tab ( Optional step for clarity of desired result )
4. Click the Project link in the top left ( Project Name next to cloud icon )

Expected Result:
- Loads 'Getting Started' tab of MQ

Actual Result:
- Loads 'Getting Started'  or 'Taks' tab of Worker

Optional expectation would be to load a more generic 'Project Overview'  that is not 'product' specific.

**Comment by thousandsofthem** [comment]
Fixed a while ago.
