### ISSUE TITLE
[HUD] Css and animations in IE9

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#19]
### IE9 Marked up

 https://www.dropbox.com/s/ecr8bl3wb530rp0/hud_ie9%20-%20highlited.png
### Chrome for comparison

https://www.dropbox.com/s/h5anc9c1z335w16/hud_chrome.png
#### IE9 Clean

https://www.dropbox.com/s/ts61gyofzpet8oe/hud_ie9.png

**Comment by jamland** [comment]
please assign all HUD style issues to me next time
regards your screenshot
- Ignore all flat colors where should be gradients for IE
  (IE doesn't support css gradients yet, but this isn't big deals for us on HUD)
- ignore all empty placeholders for inputs for IE, like this search text
  (IE doesn't sopport it yet)
- ignore bottom gears animation for IE.

– i will fix green for load bars

**Comment by jamland** [comment]
![GitHub Logo](https://www.evernote.com/shard/s38/sh/3bd1af08-e768-4a7e-aec2-107f78199c2a/f902b43fd929a004a218722ad86ca457/res/c389b719-d8eb-434c-b741-36838663e8ed/skitch.png)
