### ISSUE TITLE
HomePage Broken Layout

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#21]
https://www.dropbox.com/s/o8bi681rmppds3l/home_crome.png

Chrome Version 22.0.1229.79 m

Also appears in Safari 5.1.7 (7534.57.2) 

Console reported no errors on the page.

**Comment by odeits** [comment]
It would seem reducing the width to 305px on .home-products .your-language ul.logos-list corrects this.

**Comment by odeits** [comment]
About My Browser:
- https://aboutmybrowser.com/RJdcW4N0
- https://aboutmybrowser.com/AKYTmCnB

**Comment by codydotio** [comment]
Thanks, wasn't able to repro but I edited the width and it's on staging to go out.
