### ISSUE TITLE
[HUD] button css class does not have cursor pointer

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#23]
Buttons on the HUD for Worker do not have "hand pointer' on hover.

Steps:
1. Load "Tasks" tab of Worker product
2. Mouse over "Cancel All Tasks" button

Expected result:
- hand pointer cursor

Actual result:
- regular cursor

Note: this issue is prevalent throughout the Worker HUD but addressing it on the 'button' css class should fix it most places.

**Comment by carimura** [comment]
Should be fixed in next deploy...
