### ISSUE TITLE
Node worker timeout issue

### ISSUE THREAD

**Issue by carimura** [iron-io/issues#26]

**Comment by carimura** [comment]
Customers affected.

**Comment by abelaska** [comment]
+1
maybe node.js version upgrade is in order or implement timeout support for scheduled workers.

Those scheduled workers timeouted, hope it helps you to find the problem.
https://hud.iron.io/tq/projects/50124cab0008f20896004ec7/jobs/50bed50595bc93ec7f14b2f2
https://hud.iron.io/tq/projects/50124cab0008f20896004ec7/jobs/50be2c4395bc93ec7f142c83
https://hud.iron.io/tq/projects/50124cab0008f20896004ec7/jobs/50bfa0ec95bc93ec7f1557c3
https://hud.iron.io/tq/projects/50124cab0008f20896004ec7/jobs/50c15e3d95bc93ec7f16c3f8

**Comment by carimura** [comment]
@paddyforan did we ever resolve this?

**Comment by paddycarver** [comment]
I'm not sure. I had a bunch of diagnostic information that I sent out over the summer, but it more or less just went away on my Node/Phantom workers.

**Comment by abelaska** [comment]
It does not seem to be a HUGE problem anymore. But it happens from time to time.

**Comment by carimura** [comment]
Thanks guys... If it becomes a problem and keeps happening over time let's reopen this issue.
