### ISSUE TITLE
Node.js client library

### ISSUE THREAD

**Issue by kesavkolla** [iron-io/issues#34]
Client library for node.js would be greatly appreciated.

**Comment by treeder** [comment]
@kesavkolla which Iron.io service are you looking to use. There's a node library for IronMQ here: https://github.com/iron-io/iron_mq_node

And some docs on how to use IronWorker here: http://dev.iron.io/worker/languages/nodejs/

**Comment by kesavkolla** [comment]
I was looking for IronCache node.js library. 

Regards,
-Kesav

**Comment by abelaska** [comment]
I am using https://npmjs.org/package/memcached module to communicate with IronCache, It is much faster than REST API.

ex.
var Memcached = require('memcached'),
    memcached = new Memcached('cache-aws-us-east-1.iron.io:11211');

memcached.set('oauth', TOKEN+' '+PROJECT_ID+' '+CACHE_NAME, 0, function(err, result){
  if (err) {
    console.log('Failed to set oauth to IronCache', err);
    throw err;
  }

  if (result) {
    memcached.set('plus', payload, TTL, function(err, result){
      ....
    });
  }
});

**Comment by carimura** [comment]
There's an additional community developed library now that can be found here:

https://github.com/ahallock/node-ironio
