### ISSUE TITLE
MQ Rackspace Hud Analytics and Usage don't line up

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#4]
The Analytics graph and Usage tab report different numbers for IronMQ on Rackspace.

Expected Result:
   Analytics numbers should match Usage numbers.

Actual Result:
   Analytics shows zero on many days. Usage reports expected numbers.

Cloud: Rackspace
Product: IronMQ
ProjectId: 4fc941faf709a2551900b9d2

**Comment by treeder** [comment]
cc @rkononov

**Comment by rkononov** [comment]
fixed will be released soon
