### ISSUE TITLE
Editing Webcrawling at Scale with Nokogiri and IronWorker (Part 1)

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#5]
Article:
http://blog.iron.io/2012/08/webcrawling-at-scale-with-nokogiri-and.html

Format:
   Found
   Expected
   Reason

The reason is so you can scale the work horizontally without any additional effort just by queuing up ...
The reason is so that you can scale the work horizontally without any additional effort just by queuing up ...
Makes for an easier read.

Once the general structure of the workers have been created
One the general structure of the workers has been created
The general structure of workers is singular.

Note: One thing to note is ...
Note:
Repetitive, should be removed.

**Comment by frommww** [comment]
Thanks for the catches. Changes made. Much appreciated.
