### ISSUE TITLE
cannot create a code package with the same name of one that was deleted

### ISSUE THREAD

**Issue by calebjclark** [iron-io/issues#55]
If we delete a code package and then later try to add a code package with the same name, no package is created and an error message is returned:

HTTP 404 Error. {"msg":"Code not found. Previously deleted by user."}

We are having to delete code packages through the API to clear the error history since there is no way to do so in the interface or API. However, once we get this message, the only way to upload the code package is to manually delete the Project and create a new one. 

Is this something you can help us fix? We have about 130 code packages we are trying to upload and test before launching. 

Thanks,

Caleb

**Comment by carimura** [comment]
We'll look into this asap.... Thanks Caleb.

**Comment by treeder** [comment]
Should have this fixed this week.

**Comment by calebjclark** [comment]
Thanks. Will this just fix the bug that stopped code packages from being recreated, or will this allow us to delete old error counts for packages? The latter would be a huge help. Right now, once you get a few errors, it's very complicated to keep track of which tasks were rerun and successful vs. still needing our attention.  

-Caleb

**Comment by calebjclark** [comment]
Do you have any status updates on estimated delivery?

**Comment by treeder** [comment]
Hi @calebclark , sorry for the delay. This will mean a completely new code package with no previous stats or history. I'm trying to get it out today.

**Comment by calebjclark** [comment]
@treeder awesome!

**Comment by treeder** [comment]
@calebclark can you give this a try now? 

cc @m0use

**Comment by calebjclark** [comment]
I just tried deleting a code package and recreating it. Works great!  

Thanks so much!

Are there any plans to add the ability to remove failed tasks without deleting and recreating an entire code package?

**Comment by calebjclark** [comment]
Uh oh. I responded too fast. Although the API does allow me to delete and then recreate a code package without throwing an error, it totally wacked out my HUD. Those deleted/recreated code packages no longer show up on my Tasks Lists, and my Code page now displays a "We're sorry, but something went wrong." page.

**Comment by treeder** [comment]
Doh, we're fixing HUD right now...

**Comment by treeder** [comment]
This should all be fixed now.

**Comment by treeder** [comment]
Hi @calebclark , all good now?
