### ISSUE TITLE
Homepage IronCache Css

### ISSUE THREAD

**Issue by odeits** [iron-io/issues#6]
Setup:
   Chrome 21.0.1180.83

Steps:
   1) Load http://www.iron.io
    2) Scroll down to IronCache

Expected Result:
   Code window has "Storing Data" tab selected and "Storing Data" text is white
Actual Result:
   Code window has "Storing Data" tab selected and "Storing Data" text is grey

Notes:
   If you select another tab and then select the Storing Data tab text does get correctly set to white.

**Comment by odeits** [comment]
the problem seems to stem from this

&lt;li id="storingDataItem" class="vertical-nav" class="active" &gt;Storing Data&lt;/li&gt;

notice the class attribute is defined twice. the second definition is ignored.

should be:

&lt;li id="storingDataItem" class="vertical-nav active" &gt;Storing Data&lt;/li&gt;

**Comment by codydotio** [comment]
This is fixed and on staging-web.iron.io
