### ISSUE TITLE
Bug when reading webhook URLs?

### ISSUE THREAD

**Issue by calebjclark** [iron-io/issues#60]
I'm running into an issue with webhook urls that is completely stopping me from getting webhooks up and running. It seems that IronWorker is only reading the first query param. For example, I get a "Token required for authentication" if I post the following with valid data:

curl -X POST -d "test=testing" https://worker-aws-us-east-1.iron.io/2/projects/PROJECT_ID/tasks/webhook?code_name=CODE_NAME&oauth=TOKEN

However, if I switch the code_name and oauth params around I get a "no code_name": 

curl -X POST -d "test=testing" https://worker-aws-us-east-1.iron.io/2/projects/PROJECT_ID/tasks/webhook?oauth=TOKEN&code_name=CODE_NAME

I can't figure out any way to get an IronWorker webhook to be accepted. I see that you have documentation for this feature, but is anyone using it?

Thanks,

Caleb

**Comment by thousandsofthem** [comment]
@calebclark just wrap url in quotes: `curl -X POST ....."http://...."`
It's terminal feature, not related to iron_worker API

**Comment by calebjclark** [comment]
Ah... idiot me. Thank you for your fast response.
