### ISSUE TITLE
IronMQ attempt / reserve count...

### ISSUE THREAD

**Issue by taylorotwell** [iron-io/issues#62]
Is it at all possible for us to retrieve the number of times a given message has bene received / reserved? I know Beanstalkd has this available. Is it possible for you guys to expose this through your APIs?

This would be handy to have for the Laravel 4 framework integration!

**Comment by featalion** [comment]
As I know it's not available operation. But I assume it will not be very complicated to add the feature and send with a message as metadata like:

``` javascript
{
  id: "some id",
  body: "message body",
  receive_count: 7, // overall received
  reserve_count: 4 // peeked 3 times
}
```

Not sure it does make sense, @treeder thoughts?

**Comment by treeder** [comment]
Wow, sorry for such a slow reply, missed this one. Makes sense to me though, will update here when we do it

**Comment by andrewryno** [comment]
Any update on this? I'm going to have to start implementing my own attempt counting via some other route since we have jobs that time out and need to be deleted after X tries and handled differently.

**Comment by andrewryno** [comment]
Actually, looking at the API it looks as if reserve_count is there, which I assume is the one needed for attempt counting (since peeks aren't actual attempts).

**Comment by treeder** [comment]
Ya, this has been implemented and is returned as "reserved_count" when getting a message.
