### ISSUE TITLE
Push queue not accepting 201 response

### ISSUE THREAD

**Issue by steveyken** [iron-io/issues#67]
Reading http://dev.iron.io/mq/reference/push_queues/#how_the_endpoint_should_handle_push_messages

I can see that returning a 200 or 202 response when consuming a push queue indicates success. Is there any reason why a 201 wouldn't also be acceptable? (I've tried and a 201 is treated like a 4XX or 5XX.)

Other than that IronMQ is totally awesome. It's going to revolutionise our system integrations.

**Comment by treeder** [comment]
Hi @steveyken , it should accept 201 as you said and the fix is in. Next push to production (this week) will accept any 20X response.

**Comment by steveyken** [comment]
Excellent news. thank you!
