### ISSUE TITLE
Installing a Python module from GitHub appears to work, but doesn't....

### ISSUE THREAD

**Issue by espeed** [iron-io/issues#70]
The task log says it builds, but the Python firebase module doesn't get stored in pips...

``` bash
# Upload Command...
# $ iron_worker upload update_tweets

# define the runtime language
runtime "python"

name = "UpdateTweets"

# exec is the file that will be executed:
exec "update_tweets.py"

file "iron.json"

#pip "iron_cache"
pip "requests"
pip "-e git://github.com/mikexstudios/python-firebase.git#egg=python-firebase"

full_remote_build true
```
## Here's the builder's task log...

Successfully installed mime-types-1.23
Successfully installed rest-client-1.6.7
Successfully installed rest-2.6.0
Successfully installed iron_core-0.6.1
Successfully installed bundler-1.3.5
Successfully installed rubyzip-0.9.9
Successfully installed iron_worker_ng-0.16.4
7 gems installed
I, [2013-04-29T10:17:58.156406 #7]  INFO -- IronWorkerNG: Found workerfile with path='update_tweets.worker'
I, [2013-04-29T10:17:58.156643 #7]  INFO -- IronWorkerNG: Detected exec with path='**build**/update_tweets.py' and args='{}'
I, [2013-04-29T10:17:58.156703 #7]  INFO -- IronWorkerNG: Merging file with path='**build**/iron.json' and dest=''
I, [2013-04-29T10:17:58.156748 #7]  INFO -- IronWorkerNG: Adding python pip dependency with name='requests' and version=''
I, [2013-04-29T10:17:58.156786 #7]  INFO -- IronWorkerNG: Adding python pip dependency with name='-e git://github.com/mikexstudios/python-firebase.git#egg=python-firebase' and version=''
 NOTICE: Please install 'typhoeus' gem for optimal performance.
I, [2013-04-29T10:17:58.159897 #7]  INFO -- IronWorkerNG: Fixating pip dependencies
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  241k  100  241k    0     0   242k      0 --:--:-- --:--:-- --:--:--  267k
warning: no files found matching '_.html' under directory 'docs'
warning: no previously-included files matching '_.txt' found under directory 'docs/_build'
no previously-included directories found matching 'docs/_build/_sources'
Downloading/unpacking requests
  Running setup.py egg_info for package requests

Obtaining python-firebase from git+git://github.com/mikexstudios/python-firebase.git#egg=python-firebase
  Cloning git://github.com/mikexstudios/python-firebase.git to ./src/python-firebase
  Running setup.py egg_info for package python-firebase

Installing collected packages: requests, python-firebase
  Running setup.py install for requests

  Running setup.py develop for python-firebase

```
Creating /task/.local/lib/python2.7/site-packages/python-firebase.egg-link (link to .)
Adding python-firebase 0.1.0 to easy-install.pth file

Installed /task/src/python-firebase
```

Successfully installed requests python-firebase
Cleaning up...

**Comment by iced** [comment]
looking at this.

**Comment by iced** [comment]
pip ignores --root for git packages. submit bug to pip devs, when it's fixed, we'll be able to reset stable pip version used to install packages (using 1.3.1 now).

**Comment by espeed** [comment]
What pip install commands are you currently using...example?

Would adding something like `--install-option="--prefix=`pwd`/pips"` work?

**Comment by espeed** [comment]
NVM -- the trick is to simply not use editable mode...

``` bash
# pip "-e git://github.com/mikexstudios/python-firebase.git#egg=python-firebase"

# tarball is faster for projects with large histories
pip "https://github.com/mikexstudios/python-firebase/tarball/master" 
```

See...
- http://www.pip-installer.org/en/latest/logic.html#editable-installs
- http://guide.python-distribute.org/pip.html#installing-from-a-vcs
- https://devcenter.heroku.com/articles/python-pip
