### ISSUE TITLE
feature request: ironworker webhook callbacks

### ISSUE THREAD

**Issue by brandonhamric** [iron-io/issues#74]
I like how I get an email when a worker fails, but it would be awesome if I had direct control of what happens when a worker finishes. 

Right now my options are to launch an ec2 instance and monitor the ironworker api for task updates, timeout and wait on the process that queues the tasks, or only catch task enqueue calls that successfully make it into my worker code.

Most of these get messy if I have retry enabled for a task since I really only want to know if the all of the retries failed. Also, if my monitor sees that a worker failed on try number 1, my code may incorrectly assume that the worker failed completely. I'de love it if I could specify a callback url for "all", "error", "timeout", "Complete",  etc states so I handle this stuff however I need to and I don't have to run an extra server just for monitoring.

**Comment by carimura** [comment]
Releasing some pretty big infrastructure improvements and features over the next 1-2 weeks and then we'll come back to this.... cc @treeder @iced @edsrzf

**Comment by mwarkentin** [comment]
Any progress on this? Would love to be able to send messages to Slack about tasks.

**Comment by kmiyashiro** [comment]
:+1:

**Comment by adelevie** [comment]
hubot img mindexplode.gif

**Comment by treeder** [comment]
Hey guys, I moved this to our feature request board on Trello, please vote and comment on it there: https://trello.com/c/xVwn79L4/36-ironworker-status-callbacks
