### ISSUE TITLE
feature request: ironworker hud rerun usability

### ISSUE THREAD

**Issue by brandonhamric** [iron-io/issues#75]
Some requests to improve the usability of rerunning tasks that failed
1. Make "rerun" an ajax call. Right now it refreshes the page and I lose my place
2. Bulk rerun button. It would especially be useful to rerun only tasks that failed because of ironworker infrastructure errors
3. Show errored out tasks that have subsequently successfully ran. You do something similar with retried tasks, but seeing that an errored task ultimately passed when looking at the hud would be helpful.

**Comment by thousandsofthem** [comment]
hey @brandonhamric 
1. Yeah, good idea.
2. Probably useful thing. Need to think more about button behavior.
3. Did you mean 'rerun' tasks?

**Comment by brandonhamric** [comment]
Here's what I mean for 3. I like that the retries are tied to the auto retries are shown on the hud, but when one finishes say on the 3rd time it would be cool to see the completed task in the dropdown. My example below would be similar, but the user clicked "rerun" on the hud for the failed task. I think since they explicitly click "rerun" on the task, it should show the successful run in the dropdown with an indicator like the check that I put in before the user drops it down
![errors but finished](https://f.cloud.github.com/assets/3901798/562237/23b07078-c4a4-11e2-8841-ebf4ccb5b3d7.png)

The successful run would go at the top, i missed the sort order there

**Comment by thousandsofthem** [comment]
Great! :+1: i'm on it

**Comment by thousandsofthem** [comment]
implemented
