### ISSUE TITLE
Issue while building jython-for-android

### ISSUE THREAD

**Issue by rajatIIT** [iron-io/issues#82]
While trying to build jython-for-android, the app force closes on a live device (Nexus S) and following exception is reported  (I changed the build target from 8 to 14) : 

06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime  java.lang.NullPointerException
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at org.python.core.Py.dispatchToChecker(Py.java:2034)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at org.python.core.Py.isInstance(Py.java:1916)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at org.python.core.**builtin**.isinstance(**builtin**.java:699)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at org.python.core.Py.displayException(Py.java:1092)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at org.python.core.PyException.printStackTrace(PyException.java:79)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at org.python.core.PyException.toString(PyException.java:98)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at android.app.ActivityThread.access$600(ActivityThread.java:141)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at android.os.Handler.dispatchMessage(Handler.java:99)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at android.os.Looper.loop(Looper.java:137)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at android.app.ActivityThread.main(ActivityThread.java:5039)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at java.lang.reflect.Method.invokeNative(Native Method)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at java.lang.reflect.Method.invoke(Method.java:511)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
06:49:30.109    18570   org.jython_on_android   ERROR   AndroidRuntime      at dalvik.system.NativeStart.main(Native

Any help is appreciated.

**Comment by treeder** [comment]
Is this related to Iron.io services?

**Comment by rajatIIT** [comment]
No. I am new to github. Sorry.
