### ISSUE TITLE
--config param doesn't seem to have an effect in "iron_worker run"

### ISSUE THREAD

**Issue by daxfohl** [iron-io/issues#85]
This is under Windows 8 x64, ruby 2.0.0p247 (2013-06-27) [x64-mingw32].  So I have to upload my workers every time to test out with config settings.

**Comment by thousandsofthem** [comment]
did you try `--worker-config` ?

**Comment by daxfohl** [comment]
That just gives me "invalid option: --worker-config".

**Comment by treeder** [comment]
hi @daxfohl , what is the full command you are using with --worker-config?  --worker-config is for the upload command, not for run.

**Comment by daxfohl** [comment]
@treeder I'm not using `--worker-config`; that was just the suggestion by thousandsofthem.  I'm trying `run` with `--config`, but it has no effect.  Here's what happens when I modify my worker to do nothing but print out the args.  Below I run it once with `--config` and once without.  As you can see, the `--config` has no effect:

<pre>
C:\Users\Dax\smilestuff\worker\target>iron_worker run sendmms -p "{\"folder\":\"asdf\",\"mediaType\":1,\"photo\":\"Tulips\",\"to\":\"123456789\"}" --config "cfg.json"
------> Creating code package
        Found workerfile with path='sendmms.worker'
        Detected exec with path='sendmms.jar' and args='{}'
        Code package name is 'sendmms'
------> Running 'sendmms'
        Collected 'sendmms.jar' classpath
("-d" "C:/Users/Dax/AppData/Local/Temp/iron-worker-ng-20131013-7776-uqxx7k-container" "-payload" "C:/Users/Dax/AppData/Local/Temp/iron-worker-ng-20131013-7776-uqxx7k-container/__payload__" "-id" "0")
C:\Users\Dax\smilestuff\worker\target>iron_worker run sendmms -p "{\"folder\":\"asdf\",\"mediaType\":1,\"photo\":\"Tulips\",\"to\":\"123456789\"}"
------> Creating code package
        Found workerfile with path='sendmms.worker'
        Detected exec with path='sendmms.jar' and args='{}'
        Code package name is 'sendmms'
------> Running 'sendmms'
        Collected 'sendmms.jar' classpath
("-d" "C:/Users/Dax/AppData/Local/Temp/iron-worker-ng-20131013-1732-1uwfyin-container" "-payload" "C:/Users/Dax/AppData/Local/Temp/iron-worker-ng-20131013-1732-1uwfyin-container/__payload__" "-id" "0")
</pre>

---

The `--worker-config` is working fine in the uploaded version, successfully passing in a `-config` arg each time the worker is called.  Just the local run version isn't working, so that means I have to upload every time I want to test something that is expecting a config.  (And, using clojure, the jars end up being fairly huge and take a while to upload).  If I could get it to work locally that would be a big time saver.
