### ISSUE TITLE
API request count doubt

### ISSUE THREAD

**Issue by rsensan** [iron-io/issues#94]
Hi, 

I have integrated iron.io with Laravel framework project for delayed jobs. 
It working fine. 

On Feb 01'st I have sent 24 message to queue, in the https://hud.iron.io/mq/aws/projects/52ea631ee7791d000900001d/usage it displaying as
message: 0 
API request: 19,480

But when you see https://hud.iron.io/mq/aws/projects/52ea631ee7791d000900001d/queues here it show 24 messages

Can you explain why message count is 0 and API request count.?

Thanks & Regards
Senthil vasan | rsensan@gmail.com

**Comment by carimura** [comment]
Hey @rsensan -- best to send your request to support@iron.io. This channel isn't monitored as much.

The usage actually doesn't count messages from push queues. That might be confusing and we'll be changing that soon. So the request count and "messages all time" is the best place to get this data.
