### ISSUE TITLE
Raw markdown appearing in docs

### ISSUE THREAD

**Issue by devth** [iron-io/issues#95]
Examples:

http://dev.iron.io/worker/languages/python/
http://dev.iron.io/worker/languages/java/#deep_dive

I'm seeing raw headlines (`###`) and links (`[hud.iron.io](https://hud.iron.io)`).

**Comment by carimura** [comment]
Thanks confirmed. We will fix this today. Cc @Stephenitis @ysadka

**Comment by ysadka** [comment]
@devth thanks!
