### ISSUE TITLE
Error while running iron_worker -v

### ISSUE THREAD

**Issue by NathanHazout** [iron-io/issues#96]
I've installed the CLI on OSX running
gem install iron_worker_ng

Then I ran iron_worker -v and got:
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- json (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Library/Ruby/Gems/1.8/gems/iron_worker_ng-0.15.0/lib/iron_worker_ng/client.rb:2
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Library/Ruby/Gems/1.8/gems/iron_worker_ng-0.15.0/lib/iron_worker_ng.rb:4
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Library/Ruby/Gems/1.8/gems/iron_worker_ng-0.15.0/bin/iron_worker:6
    from /usr/bin/iron_worker:19:in `load'
    from /usr/bin/iron_worker:19

**Comment by ysadka** [comment]
To run the gem on Ruby 1.8 you must install the json gem as well.

``` sh
$ gem install json
```

Iron ruby docs:  http://dev.iron.io/worker/languages/ruby/
Iron pub chat: http://get.iron.io/chat

**Comment by NathanHazout** [comment]
The funny thing is I am running Ruby 2.1, using rbenv ... don't know why it is looking for 1.8
